### PR TITLE
[TASK] Initial TYPO3 11.5 compatibility

### PR DESCRIPTION
**Pull request by IchHabRecht**

### CODE REVIEW

**Review by ekkeguembel — APPROVED** [review]
works as designed 👍 
Known issue (form framework support broken) does not keep us from releasing

**Comment by Moongazer** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Thanks for filling out the contributors agreement @Moongazer 🚀 

@cla-bot check

**Comment by ekkeguembel** [comment]
> Is there any issue for the mentioned form framework support? I tested the current merge request with form framework for standalone and campaign forms

@IchHabRecht oh, frankly I did not even re-test that as I thought it has not yet been tackled. Will do now :)

**Review by oltmanns-leuchtfeuer — APPROVED** [review]
LGTM!

**Comment by Moongazer** [comment]
> @IchHabRecht oh, frankly I did not even re-test that as I thought it has not yet been tackled. Will do now :)

I've tested it and it works, thanks a lot @IchHabRecht!
Ready to release

**Comment by RCheesley** [comment]
I think that the outstanding author is a default user where no author details are supplied, I have seen that user pop up many times before. Therefore I believe that we are good to go based on all the actual humans writing the code having signed the CLA.

**Pull request merged**
